spring.application.name=wms

spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
spring.datasource.username=wms_user
spring.datasource.password=wms_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pajiloybaraban@gmail.com
spring.mail.password=rgpvmtbtrnwlrgrc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
wms.mail.from=pajiloybaraban@gmail.com

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

wms.app.url=http://localhost:8080
wms.frontend.url=http://localhost:5173

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.docker.compose.file=../docker-compose.yaml

wms.jwt.secret=f8gH9sK2mN5pQ8rV1vW4xZ7aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789aBcDeF
