version: '3.8'
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: wms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wms_db
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: wms_password
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: