spring.application.name=wms

spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
spring.datasource.username=wms_user
spring.datasource.password=wms_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.docker.compose.file=../docker-compose.yaml
wms.jwt.secret=f8gH9sK2mN5pQ8rV1vW4xZ7aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789aBcDeF